version: "3.1"

services:
  mysecondproject:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
    networks:
      - abc

  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sega
      POSTGRES_USER: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - abc

  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    environment:
    - PMA_HOST=db
    networks:
      - abc

networks:
  abc:
    driver: bridge