version: "2"

services:
  myfirstproject:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
    networks:
      - abc

  db:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sega
    volumes:
      - volumes1:/var/lib/mysql
    networks:
      - abc

  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    networks:
      - abc

volumes:
  volumes1:

networks:
  abc:
    driver: bridge